baseurl = "/"
googleAnalytics = ""
hasCJKLanguage = false
languageCode = "ru"
theme = "hugo-theme-cactus-plus"
title = "Antarela's site"
[params]
about = ""
archive = ""
author = "Antarela"
bio = ""
copyright = ""
customCSS = []
customJS = []
description = ""
disqusShortname = ""
enableDisqus = false
enableGoogleAnalytics = false
enableRSS = true
enableShare = true
enableSummary = true
enableToc = true
enableTwitterCard = true
facebook = ""
home = ""
iconFont = "font-awesome"
newerPosts = ""
olderPosts = ""
readMore = ""
share = ""
showLatestPosts = false
socialIconStyle = ""
subscribe = ""
subtitle404 = ""
title404 = ""
tweet = ""
twitter = ""
twitterCardImage = ""
useDescriptionReplaceSummary = false
[social]
facebook-square = "https://www.facebook.com/nodejh"
github-square = "https://www.github.com/nodejh"
twitter-square = "https://www.twitter.com/nodejh"
